const fs=require('fs');
const file='bhoc/history/index.html';
let s=fs.readFileSync(file,'utf8');
const old='<div class="event"><div class="year">1980s</div><div><h3>HIV/AIDS changes blood safety</h3><p>The HIV/AIDS crisis exposed the vulnerability inherent in transferring human biological material between people. Infectious-disease screening, donor selection and public expectations of blood safety changed profoundly, while interest in non-donor oxygen carriers intensified.</p></div></div>';
const next=`<div class="event"><div class="year">1980s</div><div><h3>HIV/AIDS changes blood safety</h3><p>The HIV/AIDS crisis exposed the vulnerability inherent in transferring human biological material between people. Infectious-disease screening, donor selection and public expectations of blood safety changed profoundly, while interest in non-donor oxygen carriers intensified.</p></div></div>
        <div class="event"><div class="year">2026</div><div><h3>The map of human blood compatibility is still expanding</h3><p>Blood-group science did not stop with ABO or Rh. In June 2026, the ISBT Working Party approved the 49th recognized human blood group system, JAMA, and it entered the official August 2026 database release. That release listed <strong>49 blood group systems and 400 red-cell antigens</strong>. More than 125 years after Landsteiner, transfusion medicine is still discovering new layers of compatibility.</p><p>This continuing expansion changes how we think about blood itself. Blood is not a simple fluid or a single laboratory number. It is a living, continuously renewing biological tissue and regulatory system with cellular, immunological, vascular and biochemical layers. Human red cells circulate for about 120 days and are replaced continuously, while platelets, leukocytes, plasma proteins and other components turn over on different timescales. The more precisely we study blood, the more complexity we find, and there is still much to understand.</p><a class="source-link" href="https://archiljali.github.io/BHOC-platform/real-world-evidence/blood-groups-history/">Blood Groups: From ABO to 49 ISBT Systems</a><br><a class="source-link" href="https://blooddatabase.isbtweb.org/release" target="_blank" rel="noopener noreferrer">ISBT August 2026 release</a></div></div>`;
if(!s.includes(old)) throw new Error('HIV event not found');
s=s.replace(old,next);
s=s.replace('Karl Landsteiner, blood groups, Red Cross blood donation','Karl Landsteiner, blood groups, blood group systems, ISBT, JAMA blood group, red cell antigens, Red Cross blood donation');
s=s.replaceAll('—','-').replaceAll('–','-');
fs.writeFileSync(file,s);
