const fs=require('fs');

// Historical Perspective
const hist='bhoc/history/index.html';
let s=fs.readFileSync(hist,'utf8');

// Breadcrumb: keep global Understand BHOC guide untouched, but use the actual hub title in article breadcrumb.
s=s.replace('<a href="/bhoc/">Understand BHOC</a> · Historical Perspective','<a href="/bhoc/">BHOC: What It Really Is &amp; Why It Exists</a> · Historical Perspective');
s=s.replace('"name":"Understand BHOC","item":"https://bhoctherapeutics.com/bhoc/"','"name":"BHOC: What It Really Is & Why It Exists","item":"https://bhoctherapeutics.com/bhoc/"');

const oldEndotoxin=`        <p><strong>This does not mean endotoxin explains the HBOC failures.</strong> Later clinical safety problems also involved NO scavenging, vasoconstriction, oxidation, methemoglobin, heme release, molecular size and indication-specific risk.</p>\n        <p><a class="source-link" href="https://pubmed.ncbi.nlm.nih.gov/1867535/" target="_blank" rel="noopener noreferrer">Quality control of hemoglobin solutions, 1991</a><br><a class="source-link" href="https://pubmed.ncbi.nlm.nih.gov/8259598/" target="_blank" rel="noopener noreferrer">Quantitative endotoxin control in cell-free hemoglobin production</a></p>\n      </div>\n\n      <div class="callout"><p><strong>Not all HBOCs are the same.</strong> A 2025 comparative review from academic investigators and FDA-affiliated authors emphasized that clinically tested HBOCs differ substantially in biochemical and biophysical characteristics and that each product must be evaluated on its own formulation, manufacturing, pharmacology, indication and benefit–risk profile.</p></div>`;

const newEndotoxin=`        <p><strong>Endotoxin cannot be established retrospectively as the single explanation for HBOC failures.</strong> Our interpretation is nevertheless that poorly controlled or incompletely characterized endotoxin burden may have made a meaningful contribution to toxicity in at least some early products and may have confounded attribution of inflammatory effects to hemoglobin itself. The contribution would have depended on the product, dose, manufacturing process and clinical context.</p>\n        <p>Other mechanisms remain important. <strong>NO scavenging is not a binary class property:</strong> its biological impact depends on molecular design, concentration, reaction kinetics, extravasation, redox behavior and formulation. Oxidation, methemoglobin formation, heme release, molecular-size distribution and indication-specific physiology can also differ substantially from one HBOC to another.</p>\n        <p><a class="source-link" href="https://pubmed.ncbi.nlm.nih.gov/1867535/" target="_blank" rel="noopener noreferrer">Quality control of hemoglobin solutions, 1991</a><br><a class="source-link" href="https://pubmed.ncbi.nlm.nih.gov/8259598/" target="_blank" rel="noopener noreferrer">Quantitative endotoxin control in cell-free hemoglobin production</a></p>\n      </div>\n\n      <div class="callout"><p><strong>Not all HBOCs are the same.</strong> The 2008 Natanson meta-analysis was a pivotal class-level safety signal across five different products and strongly influenced the field. A decade later, FDA scientists performed a side-by-side molecular and biochemical comparison of the clinically tested HBOCs and published it under the title <em>All HBOCs Are Not Created Equally</em>. A 2025 review co-authored by an FDA CBER scientist further emphasized that chemically different HBOCs should not automatically be linked to the same adverse-effect profile and should be evaluated product by product. This does not erase the historical safety signal; it changes how that signal should be interpreted for different molecules, formulations and generations.</p><p style="margin-top:12px;font-size:11px;color:#c9d9e5"><strong>Sources:</strong> Natanson et al., <em>JAMA</em>, 2008 · FDA CBER / Meng et al., 2018 · Jahr et al., <em>Transfusion</em>, 2025. Full source links are listed in References &amp; Source Notes below.</p></div>`;

if(!s.includes(oldEndotoxin)) throw new Error('Endotoxin block not found');
s=s.replace(oldEndotoxin,newEndotoxin);

// Add FDA and Natanson sources to References if not already present.
if(!s.includes('Cell-Free Hemoglobin-Based Blood Substitutes and Risk of Myocardial Infarction and Death')){
  const marker='        <li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11826291/" target="_blank" rel="noopener noreferrer">Jahr JS et al. Hemoglobin-based oxygen carriers: biochemical, biophysical differences, and safety. Transfusion. 2025.</a></li>';
  const refs=`        <li><a href="https://pubmed.ncbi.nlm.nih.gov/18443023/" target="_blank" rel="noopener noreferrer">Natanson C et al. Cell-Free Hemoglobin-Based Blood Substitutes and Risk of Myocardial Infarction and Death: A Meta-analysis. JAMA. 2008;299(19):2304–2312.</a></li>\n        <li><a href="https://www.fda.gov/vaccines-blood-biologics/science-research-biologics/fda-comparison-characteristics-hemoglobin-based-oxygen-carriers-could-guide-development-safe-and" target="_blank" rel="noopener noreferrer">U.S. FDA CBER. FDA comparison of characteristics of hemoglobin-based oxygen carriers could guide development of safe and effective products; summarizes Meng F et al., “All HBOCs Are Not Created Equally.” 2018.</a></li>\n`;
  if(s.includes(marker)) s=s.replace(marker,refs+marker);
  else s=s.replace('      </ol>\n    </section>','        <li><a href="https://pubmed.ncbi.nlm.nih.gov/18443023/" target="_blank" rel="noopener noreferrer">Natanson C et al. Cell-Free Hemoglobin-Based Blood Substitutes and Risk of Myocardial Infarction and Death: A Meta-analysis. JAMA. 2008;299(19):2304–2312.</a></li>\n        <li><a href="https://www.fda.gov/vaccines-blood-biologics/science-research-biologics/fda-comparison-characteristics-hemoglobin-based-oxygen-carriers-could-guide-development-safe-and" target="_blank" rel="noopener noreferrer">U.S. FDA CBER. All HBOCs Are Not Created Equally / comparative characterization. 2018.</a></li>\n      </ol>\n    </section>');
}

fs.writeFileSync(hist,s);

// BHOC hub: make transition to Historical Perspective unmistakable.
const hub='bhoc/index.html';
let h=fs.readFileSync(hub,'utf8');
if(!h.includes('.history-entry-card{')){
  h=h.replace('</style>',`.history-entry-card{display:block;margin:20px 0 10px;padding:22px 24px;border:1px solid #cfdcea;border-radius:16px;background:linear-gradient(145deg,#102f49,#173d5c);color:#fff;text-decoration:none;box-shadow:0 10px 28px rgba(16,47,73,.10)}.history-entry-card small{display:block;margin-bottom:7px;color:#a8d8e5;font:850 9px/1.3 Arial,sans-serif;letter-spacing:.09em;text-transform:uppercase}.history-entry-card strong{display:block;color:#fff;font-size:22px;line-height:1.2}.history-entry-card span{display:block;margin-top:10px;color:#fff;font-weight:800}.history-entry-card:hover{transform:translateY(-1px);box-shadow:0 12px 32px rgba(16,47,73,.16)}@media(max-width:620px){.history-entry-card{padding:19px 18px}.history-entry-card strong{font-size:19px}}\n  </style>`);
}
const oldCTA='<p><a class="button" href="/bhoc/history/">Read: From Bloodletting to Oxygen Therapeutics →</a></p><p style="margin-top:10px;color:#6d7a86;font-size:11px"><strong>Added 12 Sep 2026</strong> · Source-linked historical essay</p>';
const newCTA='<a class="history-entry-card" href="/bhoc/history/" aria-label="Open the full historical article From Bloodletting to Oxygen Therapeutics"><small>Full historical article · Added 12 Sep 2026</small><strong>From Bloodletting to Oxygen Therapeutics</strong><span>Open the source-linked historical timeline →</span></a>';
if(!h.includes(oldCTA)) throw new Error('History CTA not found');
h=h.replace(oldCTA,newCTA);
fs.writeFileSync(hub,h);
