const fs=require('fs');
const file='bhoc/history/index.html';
let s=fs.readFileSync(file,'utf8');
const old=`<p class="eyebrow">New-generation biological hemoglobin carrier</p><h2>HEMARINA: nature shows that hemoglobin is not one uniform molecular architecture.</h2>
      <p>HEMARINA belongs here as a new-generation biological hemoglobin-carrier pathway based on M101, the naturally extracellular hemoglobin of the marine worm <em>Arenicola marina</em>. Unlike the approximately 64 kDa tetrameric human hemoglobin molecule, M101 is a giant extracellular hemoglobin of about 3.6 MDa, organized as a hexagonal-bilayer macromolecular assembly approximately 15 × 25 nm in size and capable of binding up to 156 oxygen molecules when saturated. Its scientific importance is not that all hemoglobins behave the same, but the opposite: nature has evolved very different hemoglobin architectures for oxygen transport. Molecular size, quaternary structure, oxygen affinity, redox behavior and whether hemoglobin normally functions inside or outside a cell can differ profoundly. M101 therefore provides a strong biological example that hemoglobin-based oxygen carriers should be understood and evaluated as distinct molecular systems, not as one uniform class.</p>`;
const next=`<p class="eyebrow">A different natural source of hemoglobin</p><h2>HEMARINA: different biological source, the same fundamental oxygen-delivery function.</h2>
      <p>HEMARINA belongs here because M101 comes from a completely different animal lineage and biological source: the marine worm <em>Arenicola marina</em>. Human and other vertebrate hemoglobins are carried inside red blood cells, while M101 is a naturally extracellular hemoglobin with a much larger molecular assembly. The structures are different, but the core physiological function is shared: bind oxygen, transport it and make it available to living tissues.</p>
      <p>This is the broader biological lesson. Nature does not use one identical hemoglobin design everywhere. It uses different molecular solutions in different species and environments, while preserving the same essential oxygen-delivery purpose. Diversity in form can coexist with unity of function. Oxygen delivery is a foundational requirement of aerobic animal life, even though the specific respiratory pigments and transport systems vary across species.</p>
      <p>This cross-species principle is central to BHOC Veterinary and the BHOC Species &amp; Biodiversity Protection Initiative: <strong>Every species is different. The need for oxygen is universal.</strong></p>
      <p><a class="source-link" href="https://bhocvet.com/initiative/#science">BHOC Species &amp; Biodiversity Protection Initiative: the science bridge</a></p>`;
if(!s.includes(old)) throw new Error('HEMARINA block not found');
s=s.replace(old,next);
s=s.replaceAll('—','-').replaceAll('–','-');
fs.writeFileSync(file,s);
